version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/RoR1
hooks:
  Install:
    - location: install.sh
#       runas: root
  ValidateService:
    - location: install.sh
#       runas: root
